### ISSUE TITLE
Typo in Captive Portal?

### ISSUE THREAD

**Issue by Mark-81** [gitbls/sdm#102]
[Here](https://github.com/gitbls/sdm/blob/210897b5eb1e81a404338a81833d07c253682084/Docs/Plugins.md#wificonfig) the name of the plugin is `wificonfig` while [here](https://github.com/gitbls/sdm/blob/master/Docs/Captive-Portal.md) is always written as `wifconfig`.

**Comment by gitbls** [comment]
Clearly `wifconfig` is a typo, and will be corrected for the next release. Thanks for pointing it out.

**Comment by gitbls** [comment]
Closing issue since no further activity. Please re-open if you're still having a problem with this.
