### ISSUE TITLE
copyfile filelist requires newline at the end

### ISSUE THREAD

**Issue by dwatrous** [gitbls/sdm#118]
This is a minor and non-blocking issue. I was using `--plugin copyfile:"filelist=sdmfilelist"` in my customize to copy a set of files, but I observed that the last file in the list was not copied. I added a newline after the final file and ran the command again, at which point the file was copied as expected.

It might be enough to just add something to the docs https://github.com/gitbls/sdm/blob/master/Docs/Plugins.md#arguments-7

**Comment by gitbls** [comment]
This is true of every instance in sdm where a file is provided as input, and in fact is true of many programs on Linux that process files line-by-line.

I'm not going to locate and update every instance in sdm where this could happen unless and until there are a rash of other people running into the same issue.
