### ISSUE TITLE
VNC settings for Bookworm

### ISSUE THREAD

**Issue by timrowledge** [gitbls/sdm#158]
Whilst trying to build images for some Bookworm Pi 4/5s, (and yes, my first attepmts at using sdm so beware neophyte confusion) I was unable to get the vnc connection setup to work. 

I suspect this is a case of needing a little adaptation for the Wayland/X11 choice and the different config files used by Wayland.

My temporary work-around is to do the VNC setup on the target machine, which isn't horribly onerous for a few but might be a little irritating for a couple of dozen.

**Comment by gitbls** [comment]
TBH I've not anything with enabling VNC with Wayland, so it's not surprising doesn't work.  OTOH if you're using X11, then this is quite surprising.

I was waiting for things to die down WRT realvnc/wayland/bookworm, and also for someone to ask about it. 🤔

Can you provide a simple repro for what you're seeing? 

Thx

**Comment by timrowledge** [comment]
So far as I can tell the issue is that on a Pi 5 the default is to boot into Wayland and thus the X setup does nothing. The symptom is a tiny VNC window and the 'unable to show desktop' error when I open RealVNC on my iMac.
I did try the raspiconfig: plugin with "do_wayland" (sometihng or other) and it did nothing helpful.

The simple reproduction would be to build an image using the vnc plugin and any allowed vnc resolution, then run the result on a Pi 5, then run RealVNC on some other machine. Oh, I'm curently using RealVNC Viewer 7.8.0 (r51458) x64 (Nov 2 2023 15:35:05)

**Comment by gitbls** [comment]
Here's what I found in looking at this today on 64-bit Bookworm with Wayland enabled:

- RealVNC server does not work. It is unable to find a running X server (error logged in the system journal, viewable with journalctl), hence gets "unable to show desktop"
- If I stop RealVNC server, and do `sudo raspi-config do_vnc 0 nonint`, the wayvnc server is enabled. 
  - RealVNC viewer (at least on Windows) is able to connect to this and show the Pi desktop. TightVNC Viewer does NOT work against wayvnc, it gets "no supported security types" error
  - HOWEVER, wayvnc is not started until a user logs in on the console. Yes, this is a problem if the Pi reboots and you're not at home.

If you switch to X11, there is more flexibility. 
  - RealVNC works. You do not need to be logged in on the Pi console in order to connect
  - Virtual VNC sessions configured using sdm's `vnc` plugin work correctly
 
Based on what I've read, RealVNC may support Wayland sometime next year, but if you don't want to wait for that, your choices are:

1. Use Bookworm with Wayland and wayvnc, but wayvnc doesn't start until you login on the Pi console
2. Use Bookworm with X11 and both RealVNC and virtual VNC sessions work

Hope this helps.

**Comment by timrowledge** [comment]
> On 2023-12-29, at 5:07 PM, Benn ***@***.***> wrote:
> 
> 
> Here's what I found in looking at this today on 64-bit Bookworm with Wayland enabled:
> 
> 	• RealVNC server does not work. It is unable to find a running X server (error logged in the system journal, viewable with journalctl), hence gets "unable to show desktop"

That makes some sense. 

> 	• If I stop RealVNC server, and do sudo raspi-config do_vnc 0 nonint, the wayvnc server is enabled.

I think that corresponds to what I found

> 		• RealVNC viewer (at least on Windows) is able to connect to this and show the Pi desktop. TightVNC Viewer does NOT work against wayvnc, it gets "no supported security types" error
> 		• HOWEVER, wayvnc is not started until a user logs in on the console. Yes, this is a problem if the Pi reboots and you're not at home.

Ditto.

> If you switch to X11, there is more flexibility.
> 
> 	• RealVNC works. You do not need to be logged in on the Pi console in order to connect

Yes

> 	• Virtual VNC sessions configured using sdm's vnc plugin work correctly
> Based on what I've read, RealVNC may support Wayland sometime next year, but if you don't want to wait for that, your choices are:
> 
> 	• Use Bookworm with Wayland and wayvnc, but wayvnc doesn't start until you login on the Pi console
> 	• Use Bookworm with X11 and both RealVNC and virtual VNC sessions work
> Hope this helps.

I was initially able to get RealVNC working on a Wayland Pi by editing the .config/wayvnc/config to comment out the enable_auth=true line but that is a Pi that I have not used sdm to build for as yet.


tim
--
tim Rowledge; ***@***.***; http://www.rowledge.org/tim
I haven't lost my mind; it's backed up on tape somewhere.

**Comment by gitbls** [comment]
I didn't need to comment out the `enable_auth` line to get RealVNC working. I did exactly what I documented above.

In any case, this is a RasPiOS issue, not an sdm issue. Both RealVNC and virtual vnc desktops created with the `vnc` plugin work correctly, as expected.

If you want to use Wayland, you have to accept some compromises for now, VNC being one of them. OTOH if you want VNC to be fully functional, switch to using X11.

**Comment by gitbls** [comment]
Just-released sdm V11 has wayvnc working on Builds with Desktop. Using `--plugin vnc:wayvnc`, I am able to connect to the resulting system using RealVNC viewer on my Windows system with no config file editing required.

Please take it for a spin and LMK how it goes.

**Comment by timrowledge** [comment]
> On 2024-01-05, at 3:16 PM, Benn ***@***.***> wrote:
> 
> 
> Just-released sdm V11 has wayvnc working on Builds with Desktop. Using --plugin vnc:wayvnc, I am able to connect to the resulting system using RealVNC viewer on my Windows system with no config file editing required.
> 
> Please take it for a spin and LMK how it goes.

OK - well it took a few tries; for some reason my first go resulted in an SD card that simply wouldn't boot in the Pi 5.

I can confirm that using 
--plugin vnc: "wayvnc=1600x1200"
results in a system that boots with 
a) wayland in use
b) wayvnc configured
c) and that RealVNC on my iMac connects to it.

*However* the resolution it started with was 1280*720 for some reason. Setting it to 1600*1200 in the on-screen prefs tool and rebooting did sort that out.

Thank for fixing this issue.


tim
--
tim Rowledge; ***@***.***; http://www.rowledge.org/tim
Unprecedented performance: Nothing ever ran this slow before.

**Comment by gitbls** [comment]
Thanks for checking it out, and...whoops! I apparently was so excited that it worked at all, I didn't finish it up so that you could say `wayvnc=1600x1200` and actually have it DO something with that resolution 😵

Will get that taken care of for the next update

**Comment by timrowledge** [comment]
> On 2024-01-06, at 6:09 PM, Benn ***@***.***> wrote:
> 
> 
> Thanks for checking it out, and...whoops! I apparently was so excited that it worked at all, I didn't finish it up so that you could say wayvnc=1600x1200 and actually have it DO something with that resolution 😵
> 
> Will get that taken care of for the next update

Odd thing - I had to redo (again) trying to make adding a desktop file/association work, and this time the vnc resolution worked immediately!


tim
--
tim Rowledge; ***@***.***; http://www.rowledge.org/tim
Strange OpCodes: BBL: Branch on Burned out Light

**Comment by timrowledge** [comment]
Opps. Forgot to press CR after that --customize and so I was just re-using the prior much-fudged SD card. Oh well.

> On 2024-01-06, at 6:53 PM, Tim Rowledge ***@***.***> wrote:
> 
> 
> 
>> On 2024-01-06, at 6:09 PM, Benn ***@***.***> wrote:
>> 
>> 
>> Thanks for checking it out, and...whoops! I apparently was so excited that it worked at all, I didn't finish it up so that you could say wayvnc=1600x1200 and actually have it DO something with that resolution 😵
>> 
>> Will get that taken care of for the next update
> 
> Odd thing - I had to redo (again) trying to make adding a desktop file/association work, and this time the vnc resolution worked immediately!
> 
> 
> tim
> --
> tim Rowledge; ***@***.***; http://www.rowledge.org/tim
> Strange OpCodes: BBL: Branch on Burned out Light
> 
> 



tim
--
tim Rowledge; ***@***.***; http://www.rowledge.org/tim
Sarchasm (n): The gulf between the author of sarcastic wit and the person who doesn't get it.

**Comment by gitbls** [comment]
No worries. Just finished adding support for `wayvnc=widthXheight`. Just as you did with the prefs tool, sets the "headless" resolution. 

I'm pretty sure that it's overriden if there's a monitor attached, but I haven't tried that yet.

Also, did you notice that wayvnc doesn't start until you actually login on the console? I guess that if you want to use wayland and wayvnc reliably setting desktop autologin becomes a necessity, esp if it's headless.

Is that what you're doing?

**Comment by timrowledge** [comment]
> On 2024-01-07, at 12:30 PM, Benn ***@***.***> wrote:
> 
> 
> No worries. Just finished adding support for wayvnc=widthXheight. Just as you did with the prefs tool, sets the "headless" resolution.

Excellent; I'll try that soon, though right now my SD card is claiming to be full after --burn gets 700Mb written. No idea what is happening there but we'l try again.

> 
> I'm pretty sure that it's overriden if there's a monitor attached, but I haven't tried that yet.
> 
> Also, did you notice that wayvnc doesn't start until you actually login on the console? I guess that if you want to use wayland and wayvnc reliably setting desktop autologin becomes a necessity, esp if it's headless.
> 
> Is that what you're doing?

Yes, at least I think so; using --plugin raspiconfig:"boot_behaviour=B4"

tim
--
tim Rowledge; ***@***.***; http://www.rowledge.org/tim
Useful Latin Phrases:- Canis meus id comedit = My dog ate it.

**Comment by gitbls** [comment]
> On 2024-01-07, at 12:30 PM, Benn ***@***.***> wrote: No worries. Just finished adding support for wayvnc=widthXheight. Just as you did with the prefs tool, sets the "headless" resolution.
> Excellent; I'll try that soon, though right now my SD card is claiming to be full after --burn gets 700Mb written. 
Don't rush. It's not checked in yet. Should be there tomorrow 🤞

**Comment by gitbls** [comment]
V11.1 is posted and enables `wayvnc=widthXheight`

**Comment by timrowledge** [comment]
> On 2024-01-08, at 2:40 PM, Benn ***@***.***> wrote:
> 
> 
> V11.1 is posted and enables wayvnc=widthXheight

Excellent; worked first time (now that I completely changed the USB hardware around the dratted Pi 4 with the SSD that makes it practical to use as a builder machine!)

Now I just need to find out how to
a) create .desktop files for my loaded application that actually get hooked up
b) set the preferences for the filer windows so I get all the right options and places displayed
... so just more reams of out of date google-drivel to sift through!


tim
--
tim Rowledge; ***@***.***; http://www.rowledge.org/tim
If at first you don't succeed, call it version 1.0

**Comment by gitbls** [comment]
I haven't put anything in sdm to specifically help with .desktop files, but once you have created one you can use the `copyfile` plugin to have sdm copy it from your host system into the IMG.

For the filer window preferences, I just configured up a running system with the settings the way I want them and then save libfm.conf and pcmanfm.conf so they can be fed into new IMGs using the `lxde` plugin.

**Comment by timrowledge** [comment]
Just connecting this to #160 for the future

**Comment by gitbls** [comment]
I believe wayvnc issues are all corrected now. OP, please re-open if further issues warrant. Thx!
