### ISSUE TITLE
Firstboot overlayfs

### ISSUE THREAD

**Issue by atifghaffar** [gitbls/sdm#172]
I would like to protect the sdcard using the overlayfs

currently I am doing with the following commands

sudo raspi-config nonint enable_overlayfs
sudo raspi-config nonint enable_bootro

These i pass as --plugin runatboot:"script=./files/firstrun.sh"

Is there a better/sdm way of doing it?

thanks

**Comment by gitbls** [comment]
If the two raspi-config commands are what you run to enable it, then what you're doing seems fine to me.

**Comment by gitbls** [comment]
Was on my phone, so didn't look at this closely. You can use `--plugin raspiconfig:overlayfs` to enable the overlayfs.

But, there is no raspi-config for `enable_bootro` that I can see. 

I've not tested this previously, but will have a look at it to see what can be done.

**Comment by gitbls** [comment]
Confirmed that raspiconfig:overlayfs does not work, but will work in the next sdm release.

There will not, however, be an automatic way to disable the overlayfs on a running system. You'll need to do that manually if/when necessary.

**Comment by atifghaffar** [comment]
I was thinking of  creating a /data partition on the card along with /boot and root and then

use overlayfs on root fs

use readonly on boot

have /data read+write

this way the card is save for unclean shutdowns
if /data is corrupt, it will be fixed on the boot or manually. 

I will check what command I must pass to sdm for this partitioning

**Comment by gitbls** [comment]
This is included in the just-posted V11.4. Please test. Thx

**Comment by atifghaffar** [comment]
Thanks. I will test it. 
So it will do the equivalent of 

`raspi-config nonint enable_overlayfs`

correct?

**Comment by atifghaffar** [comment]
Tested. Works fine. I remove my local changes and use yours. 

Are you planning also to include enable_bootro support?

**Comment by atifghaffar** [comment]
Hi, Yes, I did not read that new part in the documentation. all clear now. works fine. thanks

**Comment by gitbls** [comment]
Closing as solved.
