### ISSUE TITLE
Invalid systemd version check

### ISSUE THREAD

**Issue by ykharuzhy** [gitbls/sdm#214]
I noticed this in sdm's output:

```
sdm-cparse: line 1080: [[: 256~rc3: syntax error in expression (error token is "~rc3")
```

It caused by interpreting systemd version as number here:
```
[[ "$vers" -lt "242" ]] && cmode=""
```
I have systemd 256~rc3. This error doesn't cause any troubles for versions >= 242, of course, but looks 'dirty'.

**Comment by gitbls** [comment]
Ugh. Will have a look at that. Thx.

**Comment by gitbls** [comment]
This is corrected in V12.3

**Comment by ykharuzhy** [comment]
Works, thanks

пт, 7 чэр 2024, 21:11 карыстальнік Benn ***@***.***> напісаў:

**Comment by gitbls** [comment]
Great. Thanks for taking the time to report and validate.
