### ISSUE TITLE
Multiline plugin notes

### ISSUE THREAD

**Issue by thk686** [gitbls/sdm#228]
My custom plugin needs to print some text giving instruction for configuring the wireguard server. It is proving challenging to print multiple lines using `plugin_addnote`. I cannot seem to get the escaping correct. Is there a way this could be accomplished?

**Comment by gitbls** [comment]
bash supports a multi-line string format:
```
 plugin_addnote $"
this is line 1
this is line 2
"
```
Does this do what you want?

**Comment by thk686** [comment]
Turns out I only needed one line. (Figured out a better way to configure wireguard on the command line.)
