### ISSUE TITLE
More complex settings (pi ups)

### ISSUE THREAD

**Issue by thk686** [gitbls/sdm#230]
How would I accomplish [this](https://suptronics.com/Raspberrypi/Power_mgmt/x120x-v1.0_software.html) in sdm? I can follow the command-line parts. Its the raspi-config bits I am not familiar with.

**Comment by gitbls** [comment]
Pretty much all customization is done through plugins, so your first stop for information should be https://github.com/gitbls/sdm/blob/master/Docs/Plugins.md

sdm raspiconfig documentation: https://github.com/gitbls/sdm/blob/master/Docs/Plugins.md#raspiconfig

**Comment by thk686** [comment]
Figured most of it out.
