### ISSUE TITLE
Boot from nvme?

### ISSUE THREAD

**Issue by thk686** [gitbls/sdm#232]
Can the 1pboot.conf take an option to [boot from the nvme](https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#BOOT_ORDER)?

**Comment by gitbls** [comment]
No, that's in the eeprom configuration and sdm doesn't provide any support for configuring that. It's not something you need to change regularly, so doesn't seem appropriate for sdm to support it, at least from my perspective.

**Comment by thk686** [comment]
Thanks for the info!
