### ISSUE TITLE
Installing on Fedora / Arch?

### ISSUE THREAD

**Issue by tgrushka** [gitbls/sdm#245]
Fedora (or Arch) does not support apt, but rather dnf. Maybe there are other differences.

Nonetheless, the install script fails on Fedora 40.

I would like / should be able to use this tool on Fedora, right?

Maybe in a VM... but that seems overkill.

Maybe I'll use on Docker for now... Would be nice to have a nice ready to use Docker script, if Fedora support would be difficult/take awhile.

Thanks!

**Comment by tgrushka** [comment]
Well, I guess Docker is currently an exercise in futility due to #155 and #216. Can't burn images from it because of requiring loopback devices? Don't get it, but that's what I need it for.

**Comment by gitbls** [comment]
Yea, sorry. Fedora is out of scope. You might be able to install it (just install the fedora equivalent of the  following packages:
```
binfmt-support gdisk parted qemu-user-static rsync systemd-container uuid
```
(If any of the fedora names are different that should help you understand why only Debian hosts are supported.)

Then, you can try using sdm to customize an IMG and it may work. Or it might not. It's never been tested.

If you really want to use sdm there's always the option of using the Pi system that you're building these IMGs for...

**Comment by gitbls** [comment]
Closing issue since @tgrushka did not respond re helping to make this work.
