### ISSUE TITLE
mutliple sshkey plugin commands not working 

### ISSUE THREAD

**Issue by tim-oe** [gitbls/sdm#274]
i have 2 sshkey plugin configs:

first
--plugin sshkey:"sshuser=tcronin|keyname=authorized_keys|import-key=/full-path-omitted/tcronin/authorized_keys" 
second
--plugin sshkey:"sshuser=ansible|keyname=authorized_keys|import-key=/full-path-omitted/ansible/authorized_keys" \

the second config looks to be overwriting the first file

you fixed a similar issue with the copy command
https://github.com/gitbls/sdm/issues/196

**Comment by gitbls** [comment]
Fixed in V13.4

**Comment by tim-oe** [comment]
verified fixed
