### ISSUE TITLE
sdm does not work if called from a symlink

### ISSUE THREAD

**Issue by arpj-rebola** [gitbls/sdm#35]
````
$ sudo ln -s /usr/local/sdm/sdm /usr/bin/sdm
$ sudo sdm
/usr/bin/sdm: line 606: /usr/bin/sdm-cparse: No such file or directory
/usr/bin/sdm: line 607: iswsl: command not found
? No command specified (--aptmaint --burn, --customize, --explore, --mount)
````

This issue originates in `sdm` line 605: `src=$(dirname $0)` can be replaced by e.g. `src=$(dirname "$(realpath "$0")")`.

**Comment by gitbls** [comment]
Thanks for reporting this. I'll get it into the next update.

**Comment by gitbls** [comment]
I'm nearly done with the next update and have fixed this, and I have updated EZsdmInstaller to add the link into /usr/local/bin

**Comment by gitbls** [comment]
This edit is in V7.0. Thanks again for your suggestion!
