### ISSUE TITLE
Error when using `sdm --customize`

### ISSUE THREAD

**Issue by tiefenauer** [gitbls/sdm#48]
I read through the documentation and was testing out the sample command as shown in https://github.com/gitbls/sdm/wiki/Example:-Commands. However, I cannot build a customized image, because of the following error:

```bash
* Mount IMG '2022-09-22-raspios-bullseye-arm64.img.xz'
losetup: 2022-09-22-raspios-bullseye-arm64.img.xz: Warning: file does not fit into a 512-byte sector; the end of the file will be ignored.
mount: /mnt/sdm: special device /dev/loop27p2 does not exist.
? Error mounting IMG '2022-09-22-raspios-bullseye-arm64.img.xz'
```

I'm running this on Ubuntu 22.04 (64 bit). 

Note: I changed the command from the example a bit by removing irrelevant switches and adding switches the script reported as mandatory:
removed:
- `--apps`
added:
- `--user`
- `--nowpa`

**Comment by tiefenauer** [comment]
I'm so stupid: I didn't notice I have to unzip the image first.

```bash
$ sudo apt install p7zip-full p7zip-rar
$ 7z e 2022-09-22-raspios-bullseye-arm64.img.xz
```
Afterwards it works like a charm. I'm closing this issue but leave it for other noobs so they can learn.

**Comment by gitbls** [comment]
Glad that you sorted it out. sdm checks for a ".zip" file type, but did not get it updated yet for ".xz". Will take care of this. Thanks for the reminder!
